# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lojinha do Lulu
title_en: Lulu shop
email: marlluslustosa@riseup.net
#as decricoes não estão sendo puxadas daqui, pois resolvi adicionar diretamente no arquivo footer 
description: >- # this means to ignore newlines until "baseurl:"
  Loja virtual referente aos trabalhos de Lulu Space
description_en: >- # this means to ignore newlines until "baseurl:"
  Virtual store of Lulu Space
baseurl: "" # the subpath of your site, e.g. /blog
baseurl_en: "/en"
goat_counter: lojinhacount
url: "https://lojinha.marllus.com/" # the base hostname & protocol for your site, e.g. http://example.com
defaults:
  # Default language
  -
    scope:
      path: ""
    values:
      lang: "pt-BR"
      id-ref: "na"
      baseurl: ''
  # Language for everything inside `/en`
  -
    scope:
      path: en
    values:
      lang: "en"
      #coloquei essa variavel pra auxiliar o laco na pagina post.html, onde procuro traducoes disponiveis
      id-ref: "na"
      baseurl: "/en/"
twitter_username: melolustosa
#github_username:  snipcart

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  - products
  - productsen
